/**
 * API Endpoint Functions - Generated from OpenAPI Spec
 *
 * AUTO-GENERATED by type-generator-agent from generated-docs/specs/api-spec.yaml
 * Do not edit manually - regenerate with /api-mock-refresh or re-run DESIGN.
 *
 * Each function wraps the project's API client with the correct path, method,
 * and TypeScript types from api-generated.ts.
 */

import { get, post, put } from '@/lib/api/client';
import { apiClient } from '@/lib/api/client';
import type {
  PaymentReadList,
  PaymentRead,
  PaymentBatchReadList,
  PaymentBatchRead,
  PaymentsDashboardRead,
  PaymentListParams,
  PaymentBatchListParams,
  CreatePaymentBatchRequest,
  PaymentIdsRequest,
} from '@/types/api-generated';
import type { DefaultResponse } from '@/types/api';

// ---------------------------------------------------------------------------
// Payments
// ---------------------------------------------------------------------------

/** GET /v1/payments — list all payments (optionally filtered) */
export function getPayments(params?: PaymentListParams) {
  return get<PaymentReadList>(
    '/v1/payments',
    params as Record<string, string | number | boolean | undefined>,
  );
}

/** GET /v1/payments/{id} — get a single payment by ID */
export function getPayment(id: number) {
  return get<PaymentRead>(`/v1/payments/${id}`);
}

/** PUT /v1/payments/park — park one or more payments */
export function parkPayments(
  data: PaymentIdsRequest,
  lastChangedUser?: string,
) {
  return put<void>('/v1/payments/park', data, lastChangedUser);
}

/** PUT /v1/payments/unpark — unpark one or more payments */
export function unparkPayments(
  data: PaymentIdsRequest,
  lastChangedUser?: string,
) {
  return put<void>('/v1/payments/unpark', data, lastChangedUser);
}

/** GET /v1/payments/dashboard — get dashboard metrics */
export function getDashboard() {
  return get<PaymentsDashboardRead>('/v1/payments/dashboard');
}

// ---------------------------------------------------------------------------
// Payment Batches
// ---------------------------------------------------------------------------

/** GET /v1/payment-batches — list all payment batches (optionally filtered) */
export function getPaymentBatches(params?: PaymentBatchListParams) {
  return get<PaymentBatchReadList>(
    '/v1/payment-batches',
    params as Record<string, string | number | boolean | undefined>,
  );
}

/** GET /v1/payment-batches/{id} — get a single payment batch by ID */
export function getPaymentBatch(id: number) {
  return get<PaymentBatchRead>(`/v1/payment-batches/${id}`);
}

/** POST /v1/payment-batches — create a new payment batch (initiate payment) */
export function createPaymentBatch(
  data: CreatePaymentBatchRequest,
  lastChangedUser?: string,
) {
  return post<DefaultResponse>('/v1/payment-batches', data, lastChangedUser);
}

/** POST /v1/payment-batches/{id}/download-invoice-pdf — download invoice PDF */
export function downloadInvoicePdf(id: number) {
  return apiClient<Blob>(`/v1/payment-batches/${id}/download-invoice-pdf`, {
    method: 'POST',
    isBinaryResponse: true,
  });
}

// ---------------------------------------------------------------------------
// Demo Administration
// ---------------------------------------------------------------------------

/** POST /demo/reset-demo — reset demo data to initial state */
export function resetDemo() {
  return post<void>('/demo/reset-demo');
}
