/**
 * API Types - Generated from OpenAPI Spec
 *
 * AUTO-GENERATED by type-generator-agent from generated-docs/specs/api-spec.yaml
 * Do not edit manually - regenerate with /api-mock-refresh or re-run DESIGN.
 *
 * These types correspond to the `components/schemas` section of the OpenAPI spec.
 * The existing base types (APIError, APIRequestConfig, etc.) remain in api.ts.
 */

export interface PaymentRead {
  Id?: number;
  Reference?: string;
  AgencyName?: string;
  ClaimDate?: string;
  AgentName?: string;
  LastChangedUser?: string;
  LastChangedDate?: string;
  AgentSurname?: string;
  BondAmount?: number;
  CommissionType?: string;
  GrantDate?: string;
  RegistrationDate?: string;
  Bank?: string;
  CommissionAmount?: number;
  VAT?: number;
  Status?: string;
  BatchId?: number;
}

export interface PaymentReadList {
  PaymentList?: PaymentRead[];
}

export interface PaymentBatchRead {
  Id?: number;
  CreatedDate?: string;
  Status?: string;
  Reference?: string;
  LastChangedUser?: string;
  AgencyName?: string;
  PaymentCount?: number;
  TotalCommissionAmount?: number;
  TotalVat?: number;
}

export interface PaymentBatchReadList {
  PaymentBatchList?: PaymentBatchRead[];
}

export interface PaymentStatusReportItem {
  Status?: string;
  PaymentCount?: number;
  TotalPaymentAmount?: number;
  CommissionType?: string;
  AgencyName?: string;
}

export interface ParkedPaymentsAgingReportItem {
  Range?: string;
  AgencyName?: string;
  PaymentCount?: number;
}

export interface PaymentsByAgencyReportItem {
  AgencyName?: string;
  PaymentCount?: number;
  TotalCommissionCount?: number;
  Vat?: number;
}

export interface PaymentsDashboardRead {
  PaymentStatusReport?: PaymentStatusReportItem[];
  ParkedPaymentsAgingReport?: ParkedPaymentsAgingReportItem[];
  TotalPaymentCountInLast14Days?: number;
  PaymentsByAgency?: PaymentsByAgencyReportItem[];
}

/** Request body for park and unpark operations */
export interface PaymentIdsRequest {
  PaymentIds?: number[];
}

/** Request body for creating a payment batch */
export interface CreatePaymentBatchRequest {
  PaymentIds?: number[];
}

/** Query parameters for GET /v1/payments */
export interface PaymentListParams {
  ClaimDate?: string;
  AgencyName?: string;
  Status?: string;
}

/** Query parameters for GET /v1/payment-batches */
export interface PaymentBatchListParams {
  Reference?: string;
  AgencyName?: string;
}
